from datetime import datetime
from typing import List

from pydantic import BaseModel, Field


class Alert(BaseModel):
    """Represents a raw security alert as received from a source system."""

    alert_id: str = Field(..., description="Unique identifier for the alert.")
    timestamp: datetime = Field(..., description="Timestamp when the alert was generated.")
    severity: str = Field(..., description="Severity level of the alert (e.g., low, medium, high, critical).")
    description: str = Field(..., description="Human-readable description of the alert.")


class EnrichedAlert(Alert):
    """Represents an Alert that has been enriched with LLM-based analysis."""

    llm_analysis: str = Field(..., description="Analysis text generated by the LLM for this alert.")
    mitre_techniques: List[str] = Field(
        ..., description="List of MITRE ATT&CK technique identifiers associated with the alert."
    )
    false_positive_likelihood: float = Field(
        ..., description="Estimated likelihood (as a float) that the alert is a false positive."
    )
